name: plotlyDev
channels:
  - conda-forge
  - defaults
  - plotly
  - fastai
dependencies:
# Dev libraries
  - jupyterlab
  - nbdev=2.3.12
  - fastcore=1.5.28
  - jupyterlab-unfold
# App libraries
  - plotly=5.15.0 # For image annotation
  - dash # For app containment
  - dash-bootstrap-components # For website styling
  - pandas
  - numpy
  - pip
  - pip:
    - opencv-python # This has no conda options
    - jupyterlab-code-formatter
    - black
